name: Code Review

permissions:
  contents: read
  pull-requests: write

on: 
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Log environment info
        run: |
          echo "OS: $(uname -a)"
          echo "Shell: $SHELL"
          echo "GitHub Runner: ${{ runner.os }}"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or any other version you want to specify

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Lint Code
        uses: some/lint-action@v1
        # Make sure to replace 'some/lint-action@v1' with an actual linting action.

      - uses: fluxninja/openai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false

      - name: Catch errors
        if: failure()
        run: echo "An error occurred during the workflow execution."
